name: Hit API Every 9 Minutes (10 AM to 9 PM)

on:
  schedule:

    - cron: '*/9 4-15 * * *'
  workflow_dispatch:

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Call my API
        run: |
          curl -X POST "https://staffpro.onrender.com/Api/Staff/login" \
          -H "Content-Type: application/json" \
          -d '{"Email": "demo@example.com", "Password": "demoPassword123"}'
